### ISSUE TITLE
Should we abandon the variable test suite size idea.

### ISSUE THREAD

**Issue by ambarket** [Akiira/Comp-524-program#12]
I'm thinking we should abandon the idea of having the test suites grow since we are
going to optimize size at the end anyway. You've been suggesting it for a while and I was holding onto
it because it seemed like El Ariss liked the idea but I don't think it helps the algorithm much,
the fitness function will be much simpler with out it, and I think it just makes more sense to set
the test suite size to the sum of the edges and predicates

**Comment by Akiira** [comment]
I agree, and with the size being the sum of the edges and predicates it will definitely still have enough to cover everything. This could also make evaluating fitness easier since we do not need to take size into account.

Since several parts of the code are built around variable test suite size it will probably be easier to leave most of the code the same, just pass in the same length to everyone.

**Comment by ambarket** [comment]
Done, see the commit. Basically only thing that changed was the Simulation constructor and I removed the code that actually produced the different sized suites from the population constructor and the organism mutate operator.
