### ISSUE TITLE
Negative totalUsefulness

### ISSUE THREAD

**Issue by Akiira** [Akiira/Comp-524-program#18]
I'm jumping around several different homework assignments right now but I noticed the simulation paused so I looked at the debug info and it had a negative value for totalusefullness.

The test it was on:
Testing population: 150, cutPoints: 9, mutation: 0.350000, on: HiLo

Variable Info at stop and location of stop:
![test](https://cloud.githubusercontent.com/assets/6109207/7266648/efe7e2f6-e87a-11e4-8417-b4905ad5d096.png)

I'm going to do some more testing on it, just posting this for documentation.

Also note the numOfUses  is extremly large.

edit:

Two questions:
1. What is the usesArray for in Range?
2. Whats this equation: (end - start) / 25 + 1 ?

**Comment by ambarket** [comment]
Thanks for posting this it helped me find it a lot faster.

usesArray is the array of buckets, each of size 25 that store counts of the number of times parameters in those buckets were used in test cases that provided unique coverage,

That equation then gives the number of buckets needed for the Range from start to end. The plus one was a failed attempt to mitigate issues when range sizes are not divisible by 25. I fixed this with better logic.

The bug was a problem in the logic I wrote to copy the usesArray buckets to new Ranges when splitting. The large numbers came from accessing memory outside the bounds of the source Range's usesArray.
